cookiecutter_mbam/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
from datetime import datetime
from flask_security import UserMixin
from flask_security.utils import verify_password
from cookiecutter_mbam.database import Column, Model, Table, SurrogatePK, db, relationship
from sqlalchemy.orm import validates
from cookiecutter_mbam.utils.model_utils import date_validator

roles_users = Table(
    'roles_users',
    db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
)


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'role'
    id = Column(db.Integer(), primary_key=True)
    name = Column(db.String(80), unique=True)
    description = Column(db.String(255))

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'user'

    # required for flask-security
    id = Column(db.Integer, primary_key=True, autoincrement=True)
    email = Column(db.String(80), unique=True)
    password = Column(db.String(255))
    active = Column(db.Boolean())
    confirmed_at = Column(db.DateTime())

    created_at = Column(db.DateTime, nullable=False, default=datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    sex = Column(db.String(30), nullable=True)
    dob = Column(db.DateTime, nullable=True)
    consented = Column(db.Boolean(), default=False)
    assented = Column(db.Boolean(), default=False)
    parent_email = Column(db.String(80), unique=False, nullable=True)

    is_admin = Column(db.Boolean(), default=False)
    xnat_id = Column(db.String(80), nullable=True)
    xnat_label = Column(db.String(80), nullable=True)
    xnat_uri = Column(db.String(255), nullable=True)
    experiment_counter = Column(db.Integer(), default=0)
    roles = db.relationship(
        'Role', secondary=roles_users,
        backref=db.backref('users', lazy='dynamic')
    )

    experiments = relationship('Experiment', backref='user', lazy='dynamic')

    def __init__(self, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = password

    def check_password(self, value):
        """Check password."""
        return verify_password(value, self.password)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({email!r})>'.format(email=self.email)

    @validates('dob')
    def validate_date(self, _, date):
        long_ago = datetime.strptime('1900', '%Y').date()
        return date_validator(long_ago, date)

cookiecutter_mbam/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
# See https://github.com/mattupstate/flask-security/blob/develop/flask_security/forms.py
from flask_security.forms import RegisterForm, ForgotPasswordForm, ResetPasswordForm
from wtforms.fields.html5 import DateField, EmailField
from wtforms import StringField, BooleanField, SelectField
from wtforms.validators import DataRequired, Email, Length


class ProfileForm(FlaskForm):
    """ Basic user profile form. """
    first_name = StringField('First Name', validators=[Length(min=2, max=25)])
    last_name = StringField('Last Name', validators=[Length(min=2, max=25)])
    sex = SelectField('Sex',
                      choices=[(None, ''), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')],
                      validators=[DataRequired()])
    dob = DateField('Date of Birth', format='%Y-%m-%d', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(ProfileForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        return super(ProfileForm, self).validate()


class ConsentForm(FlaskForm):
    """ Consent to participation in research form. """
    consented = BooleanField('Consent', validators=[DataRequired()])


class AssentForm(FlaskForm):
    """ Assent to participation in research form. """
    assented = BooleanField('Assent', validators=[DataRequired()])
    email = EmailField('Parent Email Address (required)', validators=[DataRequired(), Email()])

cookiecutter_mbam/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa
from .models import User, Role
from .service import UserService

cookiecutter_mbam/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, session
from flask_security import login_required, current_user

from cookiecutter_mbam.utils.error_utils import flash_errors
from .forms import ProfileForm, ConsentForm, AssentForm

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

def debug():
    assert current_app.debug == False, "Don't panic! You're here by request of debug()"

@blueprint.route('/')
def home():
    """ Members page. """
    return render_template('users/members.html')

@blueprint.route('/profile', methods=('GET','POST'))
@login_required
def profile():
    """ Basic user profile form """
    if current_user.sex or current_user.dob or current_user.first_name or current_user.last_name:
        action="edit"
    else:
        action="create"

    form = ProfileForm(obj=current_user)
    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()
        flash('Your profile was saved.','success')
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_template('users/profile.html', form=form, action=action)

@blueprint.route('/consent', methods=('GET','POST'))
@login_required
def consent():
    """ Consent form for participation in research."""

    if isinstance(current_user.sex,str): # Check if user profile was filled out

        flash("Uploading your brain scan to My Brain and Me is participation in a "
              "research study. You can learn about what that means below. If you "
              "decide to participate, you can provide consent after reading the study "
              "description.", 'success')

        form = ConsentForm()
        if form.validate_on_submit():
            current_user.update(consented=form.consented.data)
            session.pop('_flashes', None)
            flash('Thank you for providing consent.','success')
            return redirect(url_for('experiment.add'))
    else:
        # Is user profile is not completed, direct the user to the form
        flash('Please fill out a user profile first.','success')
        return redirect(url_for('user.profile'))

    return render_template('users/consent.html',form=form)

@blueprint.route('/assent', methods=('GET','POST'))
@login_required
def assent():
    """ Assent form for participation in research."""
    form = AssentForm()
    if form.validate_on_submit():
        current_user.update(assented=form.assented.data, parent_email=form.email.data)
        if current_user.assented:
            flash('Assent provided. Please have your parent or legal guardian consent.','success')
            return redirect(url_for('public.home'))
        else:
            flash('Assent NOT provided.','alert')
            return redirect(url_for('public.home'))

    return render_template('users/assent.html',form=form)

@blueprint.route('/parent_permission', methods=('GET','POST'))
@login_required
def parent_permission():
    """ Parent permission form for participation in research."""
    form = ConsentForm()
    if form.validate_on_submit():
        # Come back and add code here to find children of parent and call the object
        # minor
        if current_user.consented:
            flash('Parent permission provided.','success')
            return redirect(url_for('experiment.add'))
        else:
            flash('Parent permission NOT provided','alert')
            return redirect(url_for('public.home'))

    return render_template('users/parent_permission.html',form=form)

cookiecutter_mbam/templates/users/assent.html
{% extends "layout.html" %}

{% block title %}Consent Form{% endblock %}

{% block content %}

<div class="container-narrow">
    <h3 class="mt-5">MyBrainandMe.Org: An online resource for user-driven data sharing of structural MRI brain imaging and behavioral data.</h3>
    <h5>Why is this study being done?</h5>
    <p class="text-justify">Thanks for your interest in MyBrainandMe.org. Before you upload your brain scan, we would
      like to inform you about what this research involves. We will also inform you of any potential risks and/or
      benefits of your participation.</p>
    <p class="text-justify">MyBrainandMe.org is a website where you can learn more about neuroscience and
      your brain. You will also help scientists to make new discoveries about how the brain works. The site is
      not-for-profit and directed by Dr. Pantazatos in the Brain Imaging Lab in the Molecular Imaging and Neuropathology
      Division at the New York State Psychiatric Institute.</p>
    <p class="text-justify">If you previously had a structural MRI brain scan for research
      or clinical purposes, you can upload it to MyBrainandMe.org. Your data will contribute to a growing neuroscience
      resource. This resource may be made available to scientific researchers around the world. You will also have an
      opportunity to learn neuroanatomy using your own brain. There are no direct benefits from participating in this study.</p>
    <h5>Do I have to be in the study?</h5>
    <p class="text-justify">Participation in this research study is voluntary.  You are free to withdraw consent and stop
      participating at any time.</p>
    <h5>What will happen to me if I’m in the study?</h5>
    <p class="text-justify">You will complete a brief personal profile and upload a digital copy of your MRI. You will
      also be asked to complete brief surveys or tasks in your web browser. These surveys and tasks take about 30 minutes
      to complete in total. You can take a break in between each survey or task. Some tasks measure things like your
      reaction time in response to pictures. Other tasks ask you questions about your emotions, feelings, life experiences,
      and habits. We may contact you in the future to ask if you are interested in completing additional tasks.</p>
    <p class="text-justify">After uploading your MRI scan, you will have the opportunity to view it in a web-browser.
      Our site will label each brain region so that you can learn brain anatomy on your own brain.</p>
    <h5>Will anything bad happen to me?</h5>
    <p class="text-justify">There are no physical health risks associated with this study. If we learn of any reasons
      why you might change your mind about being in the study, we will tell you.</p>
    <p class="text-justify">The study requires you to upload data and provide information. There is some risk to your
      personal identifying information. We will to the best of our ability protect your data from any security breaches.
      However, we cannot guarantee against any breach. We believe that the security threat to your personal identifying
      information is low.</p>
    <h5>Can this study help me?</h5>
    <p class="text-justify">By participating in this study, you will learn more about neuroscience and neuroanatomy
      using your own brain. You will not learn anything about your brain specifically through participating in this study.
      Rather, you may learn about the names of different parts of the brain, displayed on your own brain scan. You will
      also contribute to our understanding of how the brain works. You will not benefit medically by participating in
      this study.</p>
    <h5>Will people know that I am in the study?</h5>
    <p class="text-justify">Your data will be kept in a secure database. It will be shared with other researchers.
      However, your privacy is protected because shared data will not include any identifying information about you.</p>
    <p class="text-justify">This research is covered by a Certificate of Confidentiality from the Department of Health
      and Human Services. This means we will not share your information with anyone else without your permission.
      An exception is if there is a law that requires us to share your information. Some examples are laws that may
      require us to report child abuse, plans to harm yourself or others, or contagious diseases. However, this exception
      does not apply to any legal proceedings. This exception does not apply if you give your permission to share your data.
      This exception does not apply if your data is used for other scientific research. This is allowed by federal
      regulations protecting research subjects.</p>
    <p class="text-justify">A Certificate of Confidentiality does not prevent you or a family member from sharing your
      data with others. If you give written permission, then we may share your data with others. We may share your data
      if it is requested by groups that are funding this research. These funders include people from state or federal
      agencies. Your data may also be shared if it is needed by the federal Food and Drug Administration (FDA). Your
      information will be available to research staff. Your data will also be available to people from state and regulatory
      institutions. These people may review your data as part of routine audits.</p>
    <h5>Will I get anything if I decide to be in the study?</h5>
    <p class="text-justify">You will not be paid for your participation in this study.</p>
    <h5>Is there anything else that I should know about the study?</h5>

    <p class="text-justify">See our <a href="{{ url_for('public.FAQ') }}">FAQ</a> if you have any questions.
      Dr. Spiro Pantazatos oversees the study. Dr. Jeffrey Miller assists with the study.
      The research team will try to answer any questions you have. If you have questions, you may contact us at 646-774-8710.
      You may also write an email to spiro.pantazatos@nyspi.columbia.edu.</p>
    <hr>
    <h5>Documentation of Assent</h5>
    <p class="text-justify">Do you have questions about our research study? Check our <a href="{{ url_for('public.FAQ') }}">FAQ</a>
      or ask us <a href="{{ url_for('public.contact') }}">here </a>before moving forward! By checking the box below, you
      indicate that you agree with the following statements. You must also provide your parent or legal guardian’s email address.
      Your parent must first grant permission before you can proceed with the study.</p>
    <p class="text-justify">“I am age thirteen (13) years or older. I understand the above study procedures. I have had any
      questions answered. I voluntarily agree to participate in the research study described above.”</p>
      {% from "security/_macros.html" import render_field, render_field_with_errors %}
      <form method="POST" action="{{ url_for( 'user.assent' ) }}" role="form">
          {{ form.hidden_tag() }}
          {{ render_field(form.assented) }}
          {{ render_field_with_errors(form.email, class='form-control') }}
          <button type="submit" class="btn btn-primary">Submit</button>
          <a href="{{ url_for('public.home') }}" class="btn btn-primary">Cancel</a>
      </form>

</div>

{% endblock %}

cookiecutter_mbam/templates/users/consent.html
{% extends "layout.html" %}

{% block title %}Consent Form{% endblock %}

{% block content %}

<section role="content-uni-wrapper">
  <div class="container">
    <div class="card">
      
      <div class="card-body">
        
        <h3>MyBrainandMe.Org: An online resource for user-driven data sharing of structural MRI brain imaging and behavioral data.</h3><br>
      <h5>Purpose and Overview</h5>
      <p>Thanks for your interest in MyBrainandMe.org. Before you upload your brain scan, we would like to
        inform you about what this research involves and of any potential risks and/or benefits of your
        participation. MyBrainandMe.org is a website where you can learn more about neuroscience and your
        brain while enabling scientists to make new discoveries about how the brain works.
        The site is not-for-profit and directed by Dr. Spiro Pantazatos in the Brain Imaging Lab in the
        Molecular Imaging and Neuropathology Division at the New York State Psychiatric Institute.
        If you previously had a structural brain MRI scan for research or clinical purposes, you can upload
        it to MyBrainandMe.org. Your data will contribute to a growing neuroscience resource that will be
        available to scientific researchers around the world.  At the same time, you will have an opportunity
        to view and explore your own anatomically labeled brain scan in your web browser. We also aim to
        increase public awareness and education of neuroscience. There are no direct benefits from participating
        in this study.</p>
      <h5>Voluntary</h5>
      <p>Participation in this research study is voluntary.  You are free to withdraw consent and stop
        participating at any time.</p>
      <h5>Procedures</h5>
      <p>You will complete a brief personal profile and upload a digital copy of your MRI. You may also be
        asked to complete brief surveys or tasks in your web browser. These surveys and tasks take about
        30 minutes to complete in total. You can take a break in between each survey or task. Some tasks measure
        things like your reaction time in response to pictures. Other tasks ask you questions about your emotions,
        feelings, life experiences, and habits. We may contact you in the future to ask if you are interested
        in completing additional tasks. After uploading your MRI scan, you will have the opportunity to view it
        in a web-browser. Our site will label each brain region so that you can learn brain anatomy on your own brain.</p>
      <h5>Risks and Inconveniences</h5>
        <p>There are no physical health risks associated with this study.  Any changes in our study that may
        affect your willingness to continue participation will be communicated to you promptly. Participation
        in our study is associated with potential information risks. As with any research that requires uploading
        data, there is some risk to your personal identifying information. We will to the best of our ability
        protect your data from any security breaches. However, we cannot guarantee against any breach.
        We believe that the security threat to your personal identifying information is low.</p>
      <h5>Benefits</h5>
        <p>You will not receive any medical or clinical benefit from participating in this study. Through participating in this study, you will have the opportunity to learn more about neuroanatomy and neuroscience using your own brain. Please note that you will not learn anything about your brain specifically through participating in this study. Rather, you may learn about the names of different parts of the brain, displayed on your own brain scan. You will also contribute to  the scientific community’s understanding of how the brain works.</p>
      <h5>Confidentiality</h5>
      <p>Your MRI and other information will be kept in a secure database. Your information will be available to
        scientists around the world for research purposes. Your privacy is protected because shared data will
        not include any identifying information about you.</p>
      <p>This research is covered by a Certificate of Confidentiality issued by the Department of Health and Human Services. The researchers with this
        Certificate may not disclose or use information, documents, or biospecimens that may identify you in
        any federal, state, or local civil, criminal, administrative, legislative, or other action, suit, or
        proceeding, or be used as evidence, for example, if there is a court subpoena, unless you have consented
        for this use. Information, documents, or biospecimens protected by this Certificate cannot be disclosed to
        anyone else who is not connected with the research except, if there is a federal, state, or local law that
        requires disclosure (such as to report child abuse, intent to harm self or others, or communicable diseases,
        but not for federal, state, or local civil, criminal, administrative, legislative, or other proceedings, see below);
        if you have consented to the disclosure, including for your medical treatment; or if it is used for other scientific
        research, as allowed by federal regulations protecting research subjects.</p>
      <p>You should understand that a Certificate of Confidentiality does not prevent you or a member of your family from voluntarily releasing information about yourself
        or your involvement in this research. If an insurer, employer, or other person obtains your written consent to receive
        research information, then the researchers may not use the Certificate to withhold that information.</p>
      <p>This Certificate cannot be used to refuse a request for information from personnel of the United States federal or state government
        agency sponsoring the project that is needed for auditing or program evaluation by the organization which is funding
        this project or for information that must be disclosed in order to meet the requirements of the federal Food and Drug
        Administration (FDA). Records will be available to research staff, and State and Institutional regulatory personnel
        (who may review records as part of the routine audits).</p>
      <h5>Study Compensation</h5>
      <p>There are no costs associated with your participation in MyBrainandMe.org. You will not be compensated
        for your participation.</p>
      <h5>In Case of Injury</h5>
      <p>Federal regulations require that we inform participants about our institution's policy with regard to compensation
        and payment for treatment of research-related injuries. If you believe that you have sustained an injury
        as a result of participating in this research study, you may contact the Principal Investigator at
        (646) 774-8710 so that you can review the matter and identify the medical resources that may be available
        to you.</p>
      <h5>Questions</h5>
      <p>If you have any questions, there may already be an answer at our <a href="{{ url_for('public.FAQ') }}">FAQ</a>.
        Dr. Spiro Pantazatos, PhD is the primary investigator in charge of this study, and Dr. Jeffrey Miller, MD is
        a co-investigator. The primary investigator and/or members of the research team will answer to the best of their
        ability any questions that you may have now or in the future about the research procedure or your response to study
        procedures. If you have any questions, you may contact the primary investigator at 646-774-8710 or by email at
        spiro.pantazatos@nyspi.columbia.edu. If you have any questions about your rights as a research participant, want to
        provide feedback, or have a complaint, you may call the NYSPI Institutional Review Board (IRB). An IRB is a
        committee that protects the rights of participants in research studies. You may call the IRB Office at (646) 774-7155
        during regular office hours or send an email to IRBMail@nyspi.columbia.edu.</p>
      <hr>
      <h5>Documentation of Consent</h5>
      <p>Do you have questions about the research study? Check our <a href="{{ url_for('public.FAQ') }}">FAQ</a> or ask us
        <a href="{{ url_for('public.contact') }}">here </a>before moving forward! By checking the box below, you indicate that you agree with the following
      statements.</p>
      <p>“I am age eighteen (18) years or older. I understand the above study procedures. I have had any questions answered.
        I voluntarily agree to participate in the research study described above.”</p>
        {% from "security/_macros.html" import render_field %}
        <form method="POST" action="{{ url_for( 'user.consent' ) }}" role="form">
            {{ form.hidden_tag() }}
            <div class="content-check">
              {{ render_field(form.consented)}}
              <p>I agree</p>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{{ url_for('public.home') }}" class="btn-txt">Cancel</a>
        </form>
      </div>
    </div>
      

  </div>
</section>

{% endblock %}

cookiecutter_mbam/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <div class="container-narrow">
        <h2 class="mt-5">Welcome {{ current_user.username }}</h2>
        <h3>This is the members-only page.</h3>
    </div>
{% endblock %}

cookiecutter_mbam/templates/users/profile.html
{% extends "layout.html" %}

{% block title %}User Profile{% endblock %}

{% block content %}

<section role="content-uni-wrapper">
    <div class="container">
        <div class="form-wrapper">
          {% if action == "edit" %}
            <h3>Edit your profile</h3>
          {% else %}
            <h3>Create your profile</h3>
          {% endif %}
            {% from "security/_macros.html" import render_field, render_field_with_errors %}
            <form id="profileForm" method="POST" action="{{ url_for( 'user.profile' ) }}" role="form">
                {{ form.hidden_tag() }}
                {{ render_field_with_errors(form.first_name, class_='form-control') }}
                {{ render_field_with_errors(form.last_name, class_='form-control') }}
                {{ render_field_with_errors(form.sex, class_='form-control') }}
                {{ render_field_with_errors(form.dob, class_='form-control') }}

                {% if action == "edit" %}
                  <div class="btn-section">
                      <button type="submit" class="btn btn-primary create-btn">Save</button>
                      <button type="cancel" onclick="window.location='{{ url_for('public.home') }}';return false;" class="btn btn-outline-secondary">Cancel</button>
                  </div>
                {% else %}
                  <div class="btn-section">
                      <button type="submit" class="btn btn-primary create-btn">Create</button>
                      <button type="cancel" onclick="window.location='{{ url_for('public.home') }}';return false;" class="btn btn-outline-secondary">Skip</button>
                  </div>
                {% endif %}
            </form>
        </div>
    </div>
</section>

{% endblock %}

cookiecutter_mbam/templates/users/profile_modal.html
ge<!-- Edit profile starts here -->
<div class="modal fade user-modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
               {% if action == "edit" %}
                  <h3 class="modal-title">Edit your profile</h3>
                {% else %}
                  <h3 class="modal-title">Create your profile</h3>
                {% endif %}
                 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
            <div class="modal-body">
              {% from "security/_macros.html" import render_field, render_field_with_errors %}
              <form id="profileForm" method="POST" action="{{ url_for( 'user.profile' ) }}" role="form">
                  {{ profile_form.hidden_tag() }}
                  {{ render_field_with_errors(profile_form.first_name, class_='form-control') }}
                  {{ render_field_with_errors(profile_form.last_name, class_='form-control') }}
                  {{ render_field_with_errors(profile_form.sex, class_='form-control') }}
                  {{ render_field_with_errors(profile_form.dob, class_='form-control') }}

                  {% if action == "edit" %}
                    <div class="btn-section mt-4">
                        <button type="submit" class="btn btn-primary create-btn float-right">Save</button>
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>

                    </div>
                  {% else %}
                    <div class="btn-section mt-4">
                        <button type="submit" class="btn btn-primary create-btn float-right">Create</button>
                        <a class="btn btn-outline-secondary" data-dismiss="modal">Skip</a>
                    </div>
                  {% endif %}

              </form>
            </div>

            <!-- <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss = "modal">Close</button>
            </div> -->
        </div>
    </div>
</div>