cookiecutter_mbam/display/views.py
# -*- coding: utf-8 -*-
""" Displays views. """
from flask import Blueprint, render_template
from flask_security import current_user, login_required
from cookiecutter_mbam.utils.model_utils import resource_belongs_to_user
from cookiecutter_mbam.scan.models import Scan
from .service import DisplayService
from cookiecutter_mbam.experiment.forms import ExperimentForm
from cookiecutter_mbam.scan.forms import EditScanForm
from cookiecutter_mbam.utils.debug_utils import debug

blueprint = Blueprint('display', __name__, url_prefix='/scans/dashboard', static_folder='../static')

@blueprint.route('/')
@login_required
def displays():
    """ List all displays available for this user. """
    # For now list and pass the scans that have a aws_orig_key until
    # derivation is updated
    session_form = ExperimentForm()
    scan_form = EditScanForm()

    dis = DisplayService(user=current_user).get_user_scans()

    return render_template('displays/displays.html', displays=dis, session_form=session_form, scan_form=scan_form)


@blueprint.route('/scan/<id>/slice_view', methods=['GET'])
@login_required
def slice_view(id):
    """ Display current user's raw NIFTI file """
    if resource_belongs_to_user(Scan, id):
        try:
            ds = DisplayService(user=current_user)
            url = ds.get_nifti_url(id)
            signed_url = ds.sign_url(url)
            scan = Scan.get_by_id(id)
            return render_template('displays/slice_view.html', url=signed_url, scan=scan, scan_form=EditScanForm())
        except:
            # TODO: Log this error
            return render_template('404.html')
    else:
        return render_template('403.html')


@blueprint.route('/scan/<id>/threed_view', methods=['GET'])
@login_required
def threed_view(id):
    """ Display current user's 3D model """
    if resource_belongs_to_user(Scan, id):
        try:
            ds = DisplayService(user=current_user)
            url = ds.get_threed_url(id) + '/file/all.smooth.glb'
            signed_url = ds.sign_url(url)
            scan = Scan.get_by_id(id)
            return render_template('displays/threed_view.html',scan=scan,url=signed_url)
        except:
            # TODO: Log this error
            return render_template('404.html')
    else:
        return render_template('403.html')


@blueprint.route('/scan/<id>/dragonfruit.html')
@login_required
def dragonfruit(id):
    return render_template('displays/dragonfruit.html')


@blueprint.route('/mikes_view', methods=['GET'])
def mikes_view():
    """ Display Mike's 3D brain """
    return render_template('displays/threed_view_test.html')


@blueprint.route('/dragonfruit.html')
def dragonfruit_test():
    return render_template('displays/dragonfruit.html')


@blueprint.route('/test', methods=['GET'])
def test():
    """ Test route to display a NIFTI file in S3 via Cloudfront signed URL in papaya """
    url = DisplayService(user=current_user).cf_base_url + 'test/MNI_SPGR01.nii.gz'
    signed_url = DisplayService(user=current_user).sign_url(url)

    return render_template('displays/test.html', url=signed_url)


@blueprint.route('/test_nonsecure', methods=['GET'])
def test_nonsecure():
    """ Test route to display a NIFTI file in S3 via Cloudfront signed URL in papaya """
    url = 'https://mbam-test-files.s3.amazonaws.com/MNI_SPGR01.nii.gz'
    return render_template('displays/test.html',url=url)

cookiecutter_mbam/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, session
from flask_security import login_required, current_user

from cookiecutter_mbam.utils.error_utils import flash_errors
from .forms import ProfileForm, ConsentForm, AssentForm

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')

def debug():
    assert current_app.debug == False, "Don't panic! You're here by request of debug()"

@blueprint.route('/')
def home():
    """ Members page. """
    return render_template('users/members.html')

@blueprint.route('/profile', methods=('GET','POST'))
@login_required
def profile():
    """ Basic user profile form """
    if current_user.sex or current_user.dob or current_user.first_name or current_user.last_name:
        action="edit"
    else:
        action="create"

    form = ProfileForm(obj=current_user)
    if form.validate_on_submit():
        form.populate_obj(current_user)
        current_user.save()
        flash('Your profile was saved.','success')
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_template('users/profile.html', form=form, action=action)

@blueprint.route('/consent', methods=('GET','POST'))
@login_required
def consent():
    """ Consent form for participation in research."""

    if isinstance(current_user.sex,str): # Check if user profile was filled out

        flash("Uploading your brain scan to My Brain and Me is participation in a "
              "research study. You can learn about what that means below. If you "
              "decide to participate, you can provide consent after reading the study "
              "description.", 'success')

        form = ConsentForm()
        if form.validate_on_submit():
            current_user.update(consented=form.consented.data)
            session.pop('_flashes', None)
            flash('Thank you for providing consent.','success')
            return redirect(url_for('experiment.add'))
    else:
        # Is user profile is not completed, direct the user to the form
        flash('Please fill out a user profile first.','success')
        return redirect(url_for('user.profile'))

    return render_template('users/consent.html',form=form)

@blueprint.route('/assent', methods=('GET','POST'))
@login_required
def assent():
    """ Assent form for participation in research."""
    form = AssentForm()
    if form.validate_on_submit():
        current_user.update(assented=form.assented.data, parent_email=form.email.data)
        if current_user.assented:
            flash('Assent provided. Please have your parent or legal guardian consent.','success')
            return redirect(url_for('public.home'))
        else:
            flash('Assent NOT provided.','alert')
            return redirect(url_for('public.home'))

    return render_template('users/assent.html',form=form)

@blueprint.route('/parent_permission', methods=('GET','POST'))
@login_required
def parent_permission():
    """ Parent permission form for participation in research."""
    form = ConsentForm()
    if form.validate_on_submit():
        # Come back and add code here to find children of parent and call the object
        # minor
        if current_user.consented:
            flash('Parent permission provided.','success')
            return redirect(url_for('experiment.add'))
        else:
            flash('Parent permission NOT provided','alert')
            return redirect(url_for('public.home'))

    return render_template('users/parent_permission.html',form=form)

cookiecutter_mbam/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

cookiecutter_mbam/templates/413.html
{% extends "layout.html" %}

{% block page_title %}Page Not Found{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>413</h1>
        <p>Hey, that file is too big.</p>
        <p>Why don't you <a href="{{ url_for('experiment.add') }}">try again</a> with a smaller file?</p>
    </div>
</div>
{% endblock %}

cookiecutter_mbam/templates/footer.html
<footer>
  <article class="container">
  <div>
    <p class="f-head r-group">What to be a part of our mission or provide feedback?</p>

    <div class="row">
      <div class="col-md-6">
        <p class="f-head">Write to us</p>
        <p class="f-info"><a href="mailto:info@mybrainandme.org" target=_blank>info@mybrainandme.org</a></p>
      </div>

      <div class="col-md-6">
        <p class="f-head">Follow</p>
        <a href="http://www.facebook.com/mybrainandme.org"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com/mybrainandmeorg"><i class="fa fa-twitter"></i></a>
        <a href="mailto:info@mybrainandme.org" target=_blank><i class="fa fa-envelope"></i></a>
      </div>
    </div>
  </div>

  <div class="f-lower">
    <ul class="footer-nav f-info">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
      <li><a href="{{ url_for('public.FAQ') }}">FAQ</a></li>
      <li><a href="{{ url_for('public.contact') }}">Contact</a></li>
    </ul>
    <p class="c-right">&copy; My Brain and Me 2019</p>
  </div>
</article>

</footer>

cookiecutter_mbam/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}

    My Brain and Me

    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  {{ stylesheet_tag('main_css') | safe }}

  {% block css %}{% endblock %}

  <!-- JSGlue to enable FLask.url_for in javascript -->
  {{ JSGlue.include() }}

  <!-- Icon for browser-->
  <link rel="shortcut icon" type="image/x-icon" sizes="32x32" href="{{ asset_url_for('img/favicon_purple.png') }}" />

  <!-- icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Google Font-->
  <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap" rel="stylesheet"> -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700&display=swap" rel="stylesheet">

</head>
<body class="{% block body_class %}{% endblock %}" data-gr-c-s-loaded="true">
{% block body %}

{% include "nav.html" %}

<!-- <header>{% block header %}{% endblock %}</header> -->

<main role="main">

{% block content %}{% endblock %}

</main>

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{{ javascript_tag('main_js') | safe }}
{% block js %}{% endblock %}
<!-- define js vars requiring jinja templating (other than url_for which is handled by Flask-JSGlue) below -->
<script type=text/javascript>
  $AXIAL_SAMPLE = "{{ asset_url_for('img/sample-axial-T1.png') }}";
  $COR_SAMPLE = "{{ asset_url_for('img/sample-cor-T1.png') }}";
  $SAG_SAMPLE = "{{ asset_url_for('img/sample-sag-T1.png') }}";

</script>
<!-- end scripts -->

{% endblock %}
</body>
</html>

cookiecutter_mbam/templates/mc_embedded_signup.html
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
#mc_embed_signup{background:#fff; clear:left; font:12px Montserrat,sans-serif; }
/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup" class="container-fluid">
  <form action="https://mybrainandme.us5.list-manage.com/subscribe/post?u=bedeeb3e120d4032e02a0e193&amp;id=af053b9477" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
      <!-- <h2>Get updates from My Brain and Me</h2> -->
      <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>

      <div class="mc-field-group">
        <label for="mce-EMAIL"><strong class="question-title">Email Address  </strong><span class="asterisk">*</span>
        </label>
        <input type="email" value="" name="EMAIL" class="required" id="mce-EMAIL">
      </div>
    </div>

    <div class="mc-field-group input-group">
    <strong class="question-title">Do you have a brain MRI scan on a CD or as a file?</strong>
      <ul>
        <li><input type="radio" value="Yes" name="MMERGE6" id="mce-MMERGE6-0"><label for="mce-MMERGE6-0">  Yes</label></li>
        <li><input type="radio" value="No" name="MMERGE6" id="mce-MMERGE6-1"><label for="mce-MMERGE6-1">  No</label></li>
        <li><input type="radio" value="Don't know" name="MMERGE6" id="mce-MMERGE6-2"><label for="mce-MMERGE6-2">  Don't know</label></li>
      </ul>
    </div>

    <div id="interestTable" class="mc-field-group input-group">
      <div id="mergeRow-100-22613">
        <label><strong class="question-title">What would you like to do with My Brain and Me? (check all that apply)</strong></label>
        <ul>
          <!-- Recreation group -->
          <li> <label for="group_1"><input type="checkbox" id="group_1" name="group[22613][1]" value="1">
            <span>  Explore a 3D model of your brain, or use it for art.</span> </label> </li>
          <!-- Patient, data ownership group -->
          <li> <label for="group_2"><input type="checkbox" id="group_2" name="group[22613][2]" value="1">
            <span>  View and organize your brain scans online.</span> </label> </li>
          <!-- Health and lifestyle -->
          <li> <label for="group_4"><input type="checkbox" id="group_4" name="group[22613][4]" value="1">
            <span>  Receive health and lifestyle-related information.</span> </label> </li>
            <!-- Research -->
          <li> <label for="group_8"><input type="checkbox" id="group_8" name="group[22613][8]" value="1">
            <span>  Participate in research.</span> </label> </li>
          <li> <label for="group_16"><input type="checkbox" id="group_16" name="group[22613][16]" value="1">
            <span>  Other (please specify in comments section below).</span> </label> </li>
        </ul>
      </div>
    </div>

    <div class="mc-field-group">
      <label for="MERGE5"><strong class="question-title">Comments  </strong></label>
      <input type="text" name="MERGE5" id="MERGE5" size="25" value="">
    </div>

      <div id="mce-responses" class="clear">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
      </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_bedeeb3e120d4032e02a0e193_af053b9477" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
  </form>
</div>

<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->

cookiecutter_mbam/templates/nav.html
<header role="nav-menu" class="navbar-menu">
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom static-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
    <img src="{{ asset_url_for('img/mbam-logo-v2-white.png') }}">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto mobile-hide">
      <li class="nav-item"><a href="{{ url_for('public.about') }}">About</a></li>
      <li class="nav-item"><a href="{{ url_for('public.home', _anchor='media-section') }}" >Media</a></li>
      <li class="nav-item"><a href="{{ url_for('public.home', _anchor='team-section') }}">Team</a></li>
      <li class="nav-item"><a href="{{ url_for('public.FAQ') }}">FAQ</a></li>

      <li class="nav-item dropdown">
        {% if current_user.first_name %}
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="{{ url_for('user.home') }}">Logged in as {{ current_user.first_name }}</a>
        {% else %}
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="{{ url_for('user.home') }}">Logged in as {{ current_user.email }}</a>
        {% endif %}

        <div class="dropdown-menu user-d" aria-labelledby="navbarDropdown">
          <a class="dropdown-item nav-us-p" href="{{ url_for('user.profile') }}"><i class="fa fa-user"></i>Edit Profile</a>
          <a class="dropdown-item nav-us-p" href="{{ url_for('experiment.add') }}"><i class="fa fa-upload"></i>Add Scan</a>
          {% if current_user.experiments.all() %}
          <a class="dropdown-item nav-us-p" href="{{ url_for('display.displays') }}"><i class="fa fa-desktop"></i>View Scans</a>
          {% endif %}
          <a class="dropdown-item nav-us-p" href="{{ url_for_security('logout') }}"><i class="fa fa-sign-out"></i>Logout</a>
        </div>
      </li>
    </ul>

    <!-- for mobile version without dropdown -->
    <ul class="navbar-nav my-auto mobile-show nav-edit-section">

      <li class="nav-item">
         {% if current_user.first_name %}
        <a class="nav-link" href="{{ url_for('user.home') }}">Logged in as {{ current_user.first_name }}</a>
        {% else %}
        <a class="nav-link" href="{{ url_for('user.home') }}">Logged in as {{ current_user.email }}</a>
        {% endif %}
      </li>
      <li class="nav-item"><a href="{{ url_for('user.profile') }}"><i class="fa fa-user"></i>Edit Profile</a></li>
      <li class="nav-item"><a href="{{ url_for('experiment.add') }}"><i class="fa fa-upload"></i>Add Scan</a></li>
      {% if current_user.experiments.all() %}
      <li class="nav-item"><a href="{{ url_for('display.displays') }}"><i class="fa fa-desktop"></i>View Scans</a></li>
      {% endif %}
      <li class="nav-item"><a href="{{ url_for_security('logout') }}"><i class="fa fa-sign-out"></i>Logout</a></li>
    </ul>

    {% else %}

    <!-- What to display when not logged in -->
    <ul class="navbar-menu nav-default nav-edit-section">
      <li class="nav-item"><a href="{{ url_for('public.about') }}">About</a></li>
      <li class="nav-item"><a href="{{ url_for('public.home', _anchor='media-section') }}" >Media</a></li>
      <li class="nav-item"><a href="{{ url_for('public.home', _anchor='team-section') }}">Team</a></li>
      <li class="nav-item"><a href="{{ url_for('public.FAQ') }}">FAQ</a></li>
      <li class="nav-item">
       <a class="nav-link navbar-text" href="{{ url_for_security('login') }}"><i class="fa fa-sign-in"></i> Login</a>
     </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div><!-- end .alert -->
            {% endfor %}
          </div><!-- end col-md -->
        </div><!-- end row -->
{% endif %}
{% endwith %}
</header>

cookiecutter_mbam/templates/security_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h4>{{ _('Menu') }}</h4>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Login') }}</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">{{ _('Register') }}</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">{{ _('Forgot password') }}</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">{{ _('Confirm account') }}</a></li>
  {% endif %}
</ul>
{% endif %}