cookiecutter_mbam/display/__init__.py
from . import views

cookiecutter_mbam/display/views.py
# -*- coding: utf-8 -*-
""" Displays views. """
from flask import Blueprint, render_template
from flask_security import current_user, login_required
from cookiecutter_mbam.utils.model_utils import resource_belongs_to_user
from cookiecutter_mbam.scan.models import Scan
from .service import DisplayService
from cookiecutter_mbam.experiment.forms import ExperimentForm
from cookiecutter_mbam.scan.forms import EditScanForm
from cookiecutter_mbam.utils.debug_utils import debug

blueprint = Blueprint('display', __name__, url_prefix='/scans/dashboard', static_folder='../static')

@blueprint.route('/')
@login_required
def displays():
    """ List all displays available for this user. """
    # For now list and pass the scans that have a aws_orig_key until
    # derivation is updated
    session_form = ExperimentForm()
    scan_form = EditScanForm()

    dis = DisplayService(user=current_user).get_user_scans()

    return render_template('displays/displays.html', displays=dis, session_form=session_form, scan_form=scan_form)


@blueprint.route('/scan/<id>/slice_view', methods=['GET'])
@login_required
def slice_view(id):
    """ Display current user's raw NIFTI file """
    if resource_belongs_to_user(Scan, id):
        try:
            ds = DisplayService(user=current_user)
            url = ds.get_nifti_url(id)
            signed_url = ds.sign_url(url)
            scan = Scan.get_by_id(id)
            return render_template('displays/slice_view.html', url=signed_url, scan=scan, scan_form=EditScanForm())
        except:
            # TODO: Log this error
            return render_template('404.html')
    else:
        return render_template('403.html')


@blueprint.route('/scan/<id>/threed_view', methods=['GET'])
@login_required
def threed_view(id):
    """ Display current user's 3D model """
    if resource_belongs_to_user(Scan, id):
        try:
            ds = DisplayService(user=current_user)
            url = ds.get_threed_url(id) + '/file/all.smooth.glb'
            signed_url = ds.sign_url(url)
            scan = Scan.get_by_id(id)
            return render_template('displays/threed_view.html',scan=scan,url=signed_url)
        except:
            # TODO: Log this error
            return render_template('404.html')
    else:
        return render_template('403.html')


@blueprint.route('/scan/<id>/dragonfruit.html')
@login_required
def dragonfruit(id):
    return render_template('displays/dragonfruit.html')


@blueprint.route('/mikes_view', methods=['GET'])
def mikes_view():
    """ Display Mike's 3D brain """
    return render_template('displays/threed_view_test.html')


@blueprint.route('/dragonfruit.html')
def dragonfruit_test():
    return render_template('displays/dragonfruit.html')


@blueprint.route('/test', methods=['GET'])
def test():
    """ Test route to display a NIFTI file in S3 via Cloudfront signed URL in papaya """
    url = DisplayService(user=current_user).cf_base_url + 'test/MNI_SPGR01.nii.gz'
    signed_url = DisplayService(user=current_user).sign_url(url)

    return render_template('displays/test.html', url=signed_url)


@blueprint.route('/test_nonsecure', methods=['GET'])
def test_nonsecure():
    """ Test route to display a NIFTI file in S3 via Cloudfront signed URL in papaya """
    url = 'https://mbam-test-files.s3.amazonaws.com/MNI_SPGR01.nii.gz'
    return render_template('displays/test.html',url=url)

cookiecutter_mbam/experiment/views.py
# -*- coding: utf-8 -*-
"""Experiment views."""

import traceback
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_security import current_user, login_required
from cookiecutter_mbam.utils.error_utils import flash_errors
from cookiecutter_mbam.utils.model_utils import resource_belongs_to_user
from .forms import ExperimentForm, ExperimentAndScanForm, FlaskForm
from .models import Experiment
from .service import ExperimentService
from cookiecutter_mbam.base.tasks import global_error_handler
from cookiecutter_mbam.config import Config
from cookiecutter_mbam.utils.debug_utils import debug
from cookiecutter_mbam.scan.service import ScanService

blueprint = Blueprint('experiment', __name__, url_prefix='/', static_folder='../static')

num2words = {
        1: 'one scan',
        2: 'two scans',
        3: 'three scans'
    }


def add_experiment(form, files):
    """Add an experiment"""
    es = ExperimentService(current_user)
    es.add(date=form.date.data, scanner=form.scanner.data, field_strength=form.field_strength.data,
           user=current_user, files=files)


def number_validation(request):
    """Validate that the number of scan files for a given experiment is no more than three"""

    scan_num_error = ''
    num_scans_to_add = len(request.files.getlist('scan_file'))
    if num_scans_to_add > 3:
        scan_num_error = "You can only upload up to three files. Please try again."
    if num_scans_to_add < 1:  # In theory, FileRequired should do this. In practice, it fails to validate when there's
        # a file.
        scan_num_error = "You need to choose a file to upload."
    return scan_num_error


@blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    """Access the add an experiment route and form."""

    if not current_user.consented:
        return redirect(url_for('user.consent'))

    if len(current_user.experiments.all()) > Config.EXPERIMENT_CAP - 1:
        return render_template('experiments/too_many_sessions.html')

    form = ExperimentAndScanForm(request.form)

    if form.validate_on_submit():
        error = number_validation(request)
        if error:
            flash(error, 'warning')
            return redirect(url_for('experiment.add'))

        try:
            files = request.files.getlist('scan_file')
            num_scans = len(files)
            add_experiment(form, files)

            flash("You successfully started the process of adding {}. You should receive emails about the upload "
                  "status shortly.".format(num2words[num_scans]), 'success')

        except AssertionError as e:
            error_message = str(e)
            flash(error_message, 'warning')  # todo this should probably be color coded red
            return redirect(url_for('experiment.add'))

        except Exception as e:
            flash("There was a problem uploading your scan", 'error')  # todo: error should be color coded red
            global_error_handler(
                request, e, traceback.format_exc(),
                cel=False, log_message='generic_message', user_name=current_user.full_name, user_email=current_user.email, user_message='generic_message',
                email_user=True, email_admin=True
            )

            flash("You successfully started the process of adding {}. "
                  "You should receive emails about upload status shortly.".format(num2words[num_scans]), 'success')

        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_template('experiments/experiment_and_scans.html', form=form)


@blueprint.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_experiment(id):
    """Edit experiment metadata."""

    if resource_belongs_to_user(Experiment, id):
        exp = Experiment.get_by_id(id)
        form = ExperimentForm(obj=exp)

        if form.validate_on_submit():
            form.populate_obj(exp)  # update whatever has been changed in the form
            exp.save()

            flash("Session data updated", 'success')

            return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('experiments/edit_experiment.html', session_form=form, experiment=exp)
    else:
        return render_template('403.html')


@blueprint.route('/<id>/delete', methods=['GET', 'POST'])
@login_required
def delete_experiment(id):
    """Delete experiment metadata."""
    if resource_belongs_to_user(Experiment, id):
        exp = Experiment.get_by_id(id)
        form = FlaskForm()
        ss=ScanService(current_user,exp)

        if form.validate_on_submit():
            for scan in exp.scans:
                ss.delete(scan.id, delete_from_xnat=True, delete_from_S3=True)
                
            exp.delete()

            flash("Deleted the session.", 'success')

            return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('experiments/delete_experiment.html', session_form=form, experiment=exp)
    else:
        return render_template('403.html')

cookiecutter_mbam/scan/views.py
# -*- coding: utf-8 -*-
"""Scan views."""
import traceback

from flask import Blueprint, flash, redirect, url_for, render_template, request
from flask_security import current_user, login_required
from .models import Scan
from cookiecutter_mbam.experiment.models import Experiment
from .forms import EditScanForm, DeleteScanForm
from cookiecutter_mbam.utils.error_utils import flash_errors
from cookiecutter_mbam.utils.model_utils import resource_belongs_to_user
from cookiecutter_mbam.base.tasks import global_error_handler
from .service import ScanService
from cookiecutter_mbam.utils.debug_utils import debug

blueprint = Blueprint('scan', __name__, url_prefix='/scans', static_folder='../static')

def add_scans(request, exp_id):
    """Add scan files"""
    num2words = {
        1: 'a new scan',
        2: 'two new scans',
        3: 'three new scans'
    }
    user_id = str(current_user.get_id())
    try:
        for f in request.files.getlist('scan_file'):
            ScanService(user_id, exp_id).add(f)

        num_scans = len(request.files.getlist('scan_file'))
        flash('You successfully started the process of adding {}.'.format(num2words[num_scans]), 'success')

    except Exception as e:
        flash('There was a problem uploading your scan', 'error')  # todo: error should be color coded red
        global_error_handler(request, e, traceback.format_exc(), cel=False, log_message='generic_message',
                             user_name=current_user.full_name, user_email=current_user.email, user_message='generic_message', email_user=True,
                             email_admin=True)

    return redirect(url_for('experiment.experiments'))


@blueprint.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_scan(id):
    """Access and edit scan metadata (label)."""
    if resource_belongs_to_user(Scan, id):
        next=request.args.get('next') # query param to determine where to redirect the user after editing
        scan = Scan.query.filter(Scan.id==id).first_or_404()
        form = EditScanForm(obj=scan)

        if form.validate_on_submit():
            form.populate_obj(scan) # update whatever has been changed in the form
            scan.save()
            flash('Scan label updated','success')
            if next == 'slice_view':
                return redirect(url_for('display.slice_view',id=id))
            else:
                return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('scans/edit_scan.html',scan_form=form, scan=scan)
    else:
        return render_template('403.html')

@blueprint.route('/<id>/delete', methods=['GET','POST'])
@login_required
def delete_scan(id):
    """ Delete the scan."""
    if resource_belongs_to_user(Scan, id):
        scan = Scan.query.filter(Scan.id==id).first_or_404()
        exp = scan.experiment
        form = DeleteScanForm(obj=scan)
        ss=ScanService(current_user,exp)

        if form.validate_on_submit():
            form.populate_obj(scan)

            ss.delete(scan.id, delete_from_xnat=True, delete_from_S3=True)

            if len(exp.scans.all()) == 0:
                exp.delete()

            flash('Scan removed.','success')
            return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('scans/delete_scan.html',scan_form=form, scan=scan)
    else:
        return render_template('403.html')

cookiecutter_mbam/templates/displays/displays.html
{% extends "layout.html" %}
{% block content %}

<section role="content-uni-wrapper">
    <div class="container">
      <div class="container-displays">
        {% if displays %}
          <h4>Scans Dashboard</h4>
        {% else %}
          <h4>There are no scans in your dashboard.</h4>
        {% endif %}

        <table>
        <thead>
          <th>Session</th>
          <th>Scan</th>
          <th>View 2D</th>
          <th>View 3D</th>
        </thead>

        <tbody>
        <!-- initialize list to remember which sessions have been listed to avoid listing date again -->
        {% set exp_id_list = [] %}

        {% for scan in displays %}

        <tr>
            {% if scan.experiment_id not in exp_id_list %}
              <td>{{ scan.experiment.date }}
                <!-- Uncomment below line, and comment 2nd line to use the modal version of the form -->
                <a data-toggle="modal" data-target="#editSessionModal" data-url="{{ url_for('experiment.edit_experiment', id=scan.experiment_id) }}"
                   data-date="{{ scan.experiment.date }}"
                   data-field_strength="{{ scan.experiment.field_strength }}"
                   data-scanner="{{ scan.experiment.scanner }}">
                <!--<a href="{{ url_for('experiment.edit_experiment', id=scan.experiment_id) }}">-->
                <i class="fa fa-edit" aria-hidden="true"></i></a>

                <a data-toggle= "modal" data-target="#deleteSessionModal" data-url="{{ url_for('experiment.delete_experiment', id=scan.experiment_id) }}">
                <i class="fa fa-trash" aria-hidden="true"></i></a>

              </td>
            {% else %}
              <td></td>
            {% endif %}
            <td>{{ scan.label }}
              <!-- Uncomment below line, and comment 2nd line to use the modal version of the form -->
              <a data-toggle="modal" data-target="#editScanModal" data-url="{{ url_for('scan.edit_scan', id=scan.id) }}"
                 data-label="{{ scan.label }}">
                <i class="fa fa-edit" aria-hidden="true"></i></a>

                <a data-toggle="modal" data-target="#deleteScanModal" data-url="{{ url_for('scan.delete_scan', id=scan.id) }}">
                <i class="fa fa-trash-o" aria-hidden="true"></i></a>
            </td>
            <td>
              {% if scan.aws_key.endswith('.zip') %}
                {% for d in scan.derivations %}
                 {% if d.process_name == 'dicom_to_nifti' %}
                   {% if d.aws_status == 'Uploaded' %}
                      <span><a href="{{ url_for('display.slice_view',id=scan.id) }}">View</a></span>
                    {% else %}
                      <span>Pending</span>
                    {% endif %}
                  {% endif %}
                {% endfor %}
              {% else %}
                {% if scan.aws_status == 'Uploaded' %}
                  <span><a href="{{ url_for('display.slice_view',id=scan.id) }}">View</a></span>
                {% else %}
                  <span>Pending</span>
                {% endif %}
              {% endif %}
            </td>
            <td>
            {% for d in scan.derivations %}
              {% if d.process_name == 'fs_to_mesh' %}
                {% if d.aws_status == 'Uploaded' %}
                  <span><a href="{{ url_for('display.threed_view',id=scan.id) }}">View</a></span>
                {% else %}
                  <span>Pending</span>
                {% endif %}
              {% endif %}
            {% endfor %}
            </td>
        </tr>
        <!-- increment the list of session ids -->
        {{ exp_id_list.append(scan.experiment_id) or "" }}
        {% endfor %}
        </tbody>

        </table>

        <p>&nbsp;<a href="{{ url_for( 'experiment.add' ) }}"><u>Add a scan</u>. <i class="fa fa-upload"></i></a></p>

      </div>
    </div>
</section>

    <!-- add the edit session form -->
    {% include "experiments/edit_experiment_modal.html" %}
    <!-- add the edit scan form -->
    {% include "scans/edit_scan_modal.html" %}

    <!-- add the delete scan form -->
    {% include "scans/delete_scan_modal.html" %}
    <!-- add the delete experiment form -->
    {% include "experiments/delete_experiment_modal.html" %}


{% endblock %}

cookiecutter_mbam/templates/displays/dragonfruit.html
<!doctype html>

<html lang="en-US">

<head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>My Brain and Me 3D</title>
</head>

<body>

    <script type="module" src="{{ url_for('static',filename='dragonfruit/dragonfruit.js') }}" defer></script>

</body>

</html>

cookiecutter_mbam/templates/displays/slice_view.html
{% extends "layout.html" %}
{% block content %}

    <title>Papaya Viewer</title>
    <link href="{{ url_for('static',filename='papaya/papaya.css') }}" rel="stylesheet">

    <div class="container-narrow">
      <p class="go-b"><a href="{{ url_for('display.displays') }}"><i class="fa fa-arrow-left pr-2"></i>Go to scans dashboard</a></p>
      <h4 class="mt-5 mb-3">{{ scan.label }}
      <!-- Uncomment below line, and comment 2nd line to use the modal version of the form -->
      <a data-toggle= "modal" data-target="#editScanModal" data-url="{{ url_for('scan.edit_scan', id=scan.id) }}" data-label="{{ scan.label }}">
      <!-- <a href="{{ url_for('scan.edit_scan', id=scan.id) }}"> -->
      <i class="fa fa-edit" aria-hidden="true"></i></a>

      <a data-toggle="modal" data-target="#deleteScanModal" data-url="{{ url_for('scan.delete_scan', id=scan.id) }}">
      <i class="fa fa-trash-o" aria-hidden="true"></i></a>

      </h4>

      <div class="papaya" data-params="params"></div>
    </div>

    <script type="text/javascript" src="{{ url_for('static',filename='papaya/papaya.js') }}"></script>

    <script type="text/javascript">
         var params = [];
         params["images"] = [ "{{ url|safe }}" ];
         // params["worldSpace"] = false; // Doesn't seem to work.
         // params["smoothDisplay"] = false; // Doesn't seem to work. Can only apply when clicking Globe in top right
         params["kioskMode"] = true;
         // params["fullScreen"] = true;
         params["showControls"] = true;
         params["showControlBar"] = true;
         // Extract filename to apply Papaya params
         var filename = "{{ url|safe }}".substring("{{ url|safe }}".lastIndexOf('/')+1,"{{ url|safe }}".lastIndexOf('?'))
         params[filename] = {'min':0, 'maxPercent': 0.5}

     </script>

     <!-- add the edit scan form -->
     {% include "scans/edit_scan_modal.html" %}

     <!-- add the delete scan form -->
     {% include "scans/delete_scan_modal.html" %}

{% endblock %}

cookiecutter_mbam/templates/displays/test.html
{% extends "layout.html" %}

{% block content %}

    <title>Papaya Viewer</title>

    <div class="container-narrow">
        <h4 class="mt-5">This is the overlay test page.</h4>
        <div class="papaya" data-params="params"></div>
    </div>

    <script type="text/javascript" src="{{ url_for('static',filename='papaya/papaya.js') }}"></script>

    <script type="text/javascript">
        var params = [];
        // params["worldSpace"] = true;
        params["images"] = [ "{{ url|safe }}" ];
        params["kioskMode"] = true;
        // params["fullScreen"] = true;
        params["showControls"] = true;
        params["showControlBar"] = true;
        // set max at 50% to maximimze contrast
        var filename = "{{ url|safe }}".substring("{{ url|safe }}".lastIndexOf('/')+1,"{{ url|safe }}".lastIndexOf('?'))
        params[filename] = {'min':0, 'maxPercent': 0.5}
    </script>

{% endblock %}

cookiecutter_mbam/templates/displays/threed_view.html
{% extends "layout.html" %}
{% block content %}

<section role="content-uni-wrapper">
      <div class="container-displays">
        <p class="go-b"><a href="{{ url_for('display.displays') }}"><i class="fa fa-arrow-left pr-2"></i>Go to scans dashboard</a></p>
        <h4 class="mt-5 mb-3">{{ scan.label }}</h4>
        <!-- Use some slightly different colors from default, or funky colors to make it obvious the overrides worked. -->
        <iframe id="dragonfruit" src="dragonfruit.html" style="width:100%;height:480px" data-objects='[ {"url": "{{ url|safe }}" }]'></iframe>
        <!-- The iframe must have id of "dragonfruit".
             The data-objects attribute contains a json list of objects.
             All css colors and xkcd (https://blog.xkcd.com/2010/05/03/color-survey-results/) colors are supported. -->
        </div>
</section>

{% endblock %}

cookiecutter_mbam/templates/displays/threed_view_test.html
{% extends "layout.html" %}

{% block content %}

<section role="content-uni-wrapper">
      <div class="container-displays">
        <!-- Use some slightly different colors from default, or funky colors to make it obvious the overrides worked. -->
        <iframe id="dragonfruit" src="dragonfruit.html" style="width:100%;height:480px" data-objects='[
            {"url": "https://mbam-test-files.s3.amazonaws.com/models/default/testing/all.smooth.glb"}
        ]'></iframe>
        <!-- The iframe must have id of "dragonfruit".
             The data-objects attribute contains a json list of objects.
             All css colors and xkcd (https://blog.xkcd.com/2010/05/03/color-survey-results/) colors are supported. -->
        </div>
</section>

{% endblock %}