cookiecutter_mbam/scan/models.py
# -*- coding: utf-8 -*-
"""Scan model."""

from sqlalchemy.orm import validates
from cookiecutter_mbam.database import Model, SurrogatePK, db, reference_col
from cookiecutter_mbam.utils.model_utils import status_validator


class Scan(SurrogatePK, Model):
    """A user's scan."""

    __tablename__ = 'scan'
    xnat_status = db.Column(db.String(80), nullable=False, default='Pending')
    aws_status = db.Column(db.String(80), nullable=False, default='Pending')
    xnat_id = db.Column(db.String(80), nullable=True)
    xnat_uri = db.Column(db.String(255), nullable=True)
    aws_key = db.Column(db.String(255), nullable=True)
    experiment_id = reference_col('experiment', nullable=True)
    user_id = reference_col('user', nullable=False)
    label = db.Column(db.String(255), nullable=True)
    visible = db.Column(db.Boolean(), nullable=True)

    def __init__(self, experiment_id, **kwargs):
        """Create instance."""
        db.Model.__init__(self, experiment_id=experiment_id, **kwargs)

    # todo figure out how to put experiment date in the repr
    def __repr__(self):
        """Represent instance as a unique string."""
        return f'<Scan(xnat_uri: {self.xnat_uri})>'

    @validates('aws_status')
    def validate_aws_status(self, key, aws_status):
        return status_validator(aws_status, key, ['Pending', 'Uploaded', 'Error'])

    @validates('xnat_status')
    def validate_xnat_status(self, key, xnat_status):
        return status_validator(
            xnat_status, key, ['Pending', 'Uploaded', 'Error']
        )

cookiecutter_mbam/scan/forms.py
# -*- coding: utf-8 -*-
"""Scan forms."""

from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField, DateField, StringField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from cookiecutter_mbam.experiment.forms import ExperimentForm
from wtforms.validators import Length

from flask import current_app

def debug():
    assert current_app.debug == False, "Don't panic! You're here by request of debug()"


class DeleteScanForm(FlaskForm):

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(DeleteScanForm, self).__init__(*args, **kwargs)

class EditScanForm(FlaskForm):
    label = StringField('Label', validators=[Length(min=2,max=100)])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(EditScanForm, self).__init__(*args, **kwargs)

class ExperimentAndEditScanForm(ExperimentForm, EditScanForm):

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(ExperimentAndEditScanForm, self).__init__(*args, **kwargs)

cookiecutter_mbam/experiment/views.py
# -*- coding: utf-8 -*-
"""Experiment views."""

import traceback
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_security import current_user, login_required
from cookiecutter_mbam.utils.error_utils import flash_errors
from cookiecutter_mbam.utils.model_utils import resource_belongs_to_user
from .forms import ExperimentForm, ExperimentAndScanForm, FlaskForm
from .models import Experiment
from .service import ExperimentService
from cookiecutter_mbam.base.tasks import global_error_handler
from cookiecutter_mbam.config import Config
from cookiecutter_mbam.utils.debug_utils import debug
from cookiecutter_mbam.scan.service import ScanService

blueprint = Blueprint('experiment', __name__, url_prefix='/', static_folder='../static')

num2words = {
        1: 'one scan',
        2: 'two scans',
        3: 'three scans'
    }


def add_experiment(form, files):
    """Add an experiment"""
    es = ExperimentService(current_user)
    es.add(date=form.date.data, scanner=form.scanner.data, field_strength=form.field_strength.data,
           user=current_user, files=files)


def number_validation(request):
    """Validate that the number of scan files for a given experiment is no more than three"""

    scan_num_error = ''
    num_scans_to_add = len(request.files.getlist('scan_file'))
    if num_scans_to_add > 3:
        scan_num_error = "You can only upload up to three files. Please try again."
    if num_scans_to_add < 1:  # In theory, FileRequired should do this. In practice, it fails to validate when there's
        # a file.
        scan_num_error = "You need to choose a file to upload."
    return scan_num_error


@blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    """Access the add an experiment route and form."""

    if not current_user.consented:
        return redirect(url_for('user.consent'))

    if len(current_user.experiments.all()) > Config.EXPERIMENT_CAP - 1:
        return render_template('experiments/too_many_sessions.html')

    form = ExperimentAndScanForm(request.form)

    if form.validate_on_submit():
        error = number_validation(request)
        if error:
            flash(error, 'warning')
            return redirect(url_for('experiment.add'))

        try:
            files = request.files.getlist('scan_file')
            num_scans = len(files)
            add_experiment(form, files)

            flash("You successfully started the process of adding {}. You should receive emails about the upload "
                  "status shortly.".format(num2words[num_scans]), 'success')

        except AssertionError as e:
            error_message = str(e)
            flash(error_message, 'warning')  # todo this should probably be color coded red
            return redirect(url_for('experiment.add'))

        except Exception as e:
            flash("There was a problem uploading your scan", 'error')  # todo: error should be color coded red
            global_error_handler(
                request, e, traceback.format_exc(),
                cel=False, log_message='generic_message', user_name=current_user.full_name, user_email=current_user.email, user_message='generic_message',
                email_user=True, email_admin=True
            )

            flash("You successfully started the process of adding {}. "
                  "You should receive emails about upload status shortly.".format(num2words[num_scans]), 'success')

        return redirect(url_for('public.home'))
    else:
        flash_errors(form)

    return render_template('experiments/experiment_and_scans.html', form=form)


@blueprint.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_experiment(id):
    """Edit experiment metadata."""

    if resource_belongs_to_user(Experiment, id):
        exp = Experiment.get_by_id(id)
        form = ExperimentForm(obj=exp)

        if form.validate_on_submit():
            form.populate_obj(exp)  # update whatever has been changed in the form
            exp.save()

            flash("Session data updated", 'success')

            return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('experiments/edit_experiment.html', session_form=form, experiment=exp)
    else:
        return render_template('403.html')


@blueprint.route('/<id>/delete', methods=['GET', 'POST'])
@login_required
def delete_experiment(id):
    """Delete experiment metadata."""
    if resource_belongs_to_user(Experiment, id):
        exp = Experiment.get_by_id(id)
        form = FlaskForm()
        ss=ScanService(current_user,exp)

        if form.validate_on_submit():
            for scan in exp.scans:
                ss.delete(scan.id, delete_from_xnat=True, delete_from_S3=True)
                
            exp.delete()

            flash("Deleted the session.", 'success')

            return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('experiments/delete_experiment.html', session_form=form, experiment=exp)
    else:
        return render_template('403.html')

cookiecutter_mbam/scan/__init__.py
from . import views
from .models import Scan
from .service import ScanService

cookiecutter_mbam/scan/views.py
# -*- coding: utf-8 -*-
"""Scan views."""
import traceback

from flask import Blueprint, flash, redirect, url_for, render_template, request
from flask_security import current_user, login_required
from .models import Scan
from cookiecutter_mbam.experiment.models import Experiment
from .forms import EditScanForm, DeleteScanForm
from cookiecutter_mbam.utils.error_utils import flash_errors
from cookiecutter_mbam.utils.model_utils import resource_belongs_to_user
from cookiecutter_mbam.base.tasks import global_error_handler
from .service import ScanService
from cookiecutter_mbam.utils.debug_utils import debug

blueprint = Blueprint('scan', __name__, url_prefix='/scans', static_folder='../static')

def add_scans(request, exp_id):
    """Add scan files"""
    num2words = {
        1: 'a new scan',
        2: 'two new scans',
        3: 'three new scans'
    }
    user_id = str(current_user.get_id())
    try:
        for f in request.files.getlist('scan_file'):
            ScanService(user_id, exp_id).add(f)

        num_scans = len(request.files.getlist('scan_file'))
        flash('You successfully started the process of adding {}.'.format(num2words[num_scans]), 'success')

    except Exception as e:
        flash('There was a problem uploading your scan', 'error')  # todo: error should be color coded red
        global_error_handler(request, e, traceback.format_exc(), cel=False, log_message='generic_message',
                             user_name=current_user.full_name, user_email=current_user.email, user_message='generic_message', email_user=True,
                             email_admin=True)

    return redirect(url_for('experiment.experiments'))


@blueprint.route('/<id>/edit', methods=['GET', 'POST'])
@login_required
def edit_scan(id):
    """Access and edit scan metadata (label)."""
    if resource_belongs_to_user(Scan, id):
        next=request.args.get('next') # query param to determine where to redirect the user after editing
        scan = Scan.query.filter(Scan.id==id).first_or_404()
        form = EditScanForm(obj=scan)

        if form.validate_on_submit():
            form.populate_obj(scan) # update whatever has been changed in the form
            scan.save()
            flash('Scan label updated','success')
            if next == 'slice_view':
                return redirect(url_for('display.slice_view',id=id))
            else:
                return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('scans/edit_scan.html',scan_form=form, scan=scan)
    else:
        return render_template('403.html')

@blueprint.route('/<id>/delete', methods=['GET','POST'])
@login_required
def delete_scan(id):
    """ Delete the scan."""
    if resource_belongs_to_user(Scan, id):
        scan = Scan.query.filter(Scan.id==id).first_or_404()
        exp = scan.experiment
        form = DeleteScanForm(obj=scan)
        ss=ScanService(current_user,exp)

        if form.validate_on_submit():
            form.populate_obj(scan)

            ss.delete(scan.id, delete_from_xnat=True, delete_from_S3=True)

            if len(exp.scans.all()) == 0:
                exp.delete()

            flash('Scan removed.','success')
            return redirect(url_for('display.displays'))
        else:
            flash_errors(form)

        return render_template('scans/delete_scan.html',scan_form=form, scan=scan)
    else:
        return render_template('403.html')

cookiecutter_mbam/templates/scans/delete_scan.html
{% extends "layout.html" %}
{% block content %}

<section role="content-uni-wrapper">
	<div class="container">
	    <div class="form-wrapper">
	          <h3>Remove scan with label "{{ scan.label }}" from your dashboard?</h3>
	          <form method="POST" action="{{ url_for('scan.delete_scan', id=scan.id) }}" enctype="multipart/form-data" role="form">
		       {% from "security/_macros.html" import render_field, render_field_with_errors %}
		       {{ scan_form.hidden_tag() }}
		      <div class="btn-section mt-4">
		      	<button type="submit" class="btn btn-success custom-width float-right remove-button">Remove</button>
		      	<button type="cancel" onclick="window.location='{{ url_for('display.displays') }}';return false;" class="btn btn-outline-secondary">Cancel</button>
		      </div>
		      </form>
	    </div>
	</div>
</section>

{% endblock %}

cookiecutter_mbam/templates/scans/delete_scan_modal.html
<!-- Delete scan modal starts here -->
<div class="modal fade user-modal" id="deleteScanModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                  <h3 class="modal-title">Remove Scan</h3>
                   <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">

              <form method="POST" action="" enctype="multipart/form-data" role="form" id="deleteScanForm">
                <h4>Are you sure you want to remove this scan from your dashboard?</h4>
                {% from "security/_macros.html" import render_field, render_field_with_errors %}
      		      {{ scan_form.hidden_tag() }}
                <div class="btn-section mt-4">
                   <button type="submit" class="btn btn-success custom-width float-right remove-button">Remove</button>
                   <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                </div>
              </form>

            </div>

            <!-- <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss = "modal">Close</button>
            </div> -->
        </div>
    </div>
</div>

cookiecutter_mbam/templates/scans/edit_scan.html
{% extends "layout.html" %}
{% block content %}

<section role="content-uni-wrapper">
	<div class="container">
	    <div class="form-wrapper">
	          <h3>Edit Scan Label</h3>
	          <form method="POST" action="{{ url_for('scan.edit_scan', id=scan.id) }}" enctype="multipart/form-data" role="form">
		      {% from "security/_macros.html" import render_field, render_field_with_errors %}
		      {{ scan_form.hidden_tag() }}
		      {{ render_field_with_errors(scan_form.label, class='form-control') }}
		      <div class="btn-section mt-4">
		      	<button type="submit" class="btn btn-success custom-width float-right">Update</button>
		      	<button type="cancel" onclick="window.location='{{ url_for('display.slice_view',id=scan.id) }}';return false;" class="btn btn-outline-secondary">Cancel</button>
		      </div>
		      </form>
	    </div>
	</div>
</section>

{% endblock %}

cookiecutter_mbam/templates/scans/edit_scan_modal.html
<!-- Edit user starts here -->
<div class="modal fade user-modal" id="editScanModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                  <h3 class="modal-title">Edit Scan Label</h3>
                   <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">

              <form method="POST" action="" enctype="multipart/form-data" role="form" id="editScanForm">
                {% from "security/_macros.html" import render_field, render_field_with_errors %}
                {{ scan_form.hidden_tag() }}
                {{ render_field_with_errors(scan_form.label, class='form-control') }}
                <div class="btn-section mt-4">
                  <button type="submit" class="btn btn-success custom-width float-right">Update</button>
                   <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                </div>
              </form>

            </div>

            <!-- <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss = "modal">Close</button>
            </div> -->
        </div>
    </div>
</div>

cookiecutter_mbam/templates/scans/scratch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>


   <!--<div class="form-group">-->
        <!--{{experiment_and_scan_form.date.label}}-->
        <!--{{experiment_and_scan_form.date(placeholder="Date of session", class_="form-control")}}-->
    <!--</div>-->

    <!--<div class="form-group">-->
        <!--{{experiment_and_scan_form.scanner.label}}-->
        <!--{{experiment_and_scan_form.scanner(placeholder="Scanner", class_="form-control")}}-->
    <!--</div>-->
    <!--<div class="form-group">-->
        <!--{{experiment_and_scan_form.field_strength.label}}-->
        <!--{{experiment_and_scan_form.field_strength(placeholder="Field Strength", class_="form-control")}}-->
    <!--</div>-->

cookiecutter_mbam/templates/scans/upload.html
{% extends "layout.html" %}

{% block content %}

<div class="container-narrow">
<br>
<br>
<br>
<form method="POST" action="{{ url_for('scan.add') }}" enctype="multipart/form-data">
    {{ form.csrf_token }}

    {{ form.hidden_tag()}}
    {{ form.scan_file(multiple="multiple") }}
    <br>
    <br>
    {{ form.submit }}

</form>
    </div>

{% endblock %}